on:
  push:
    branches: [ master ]         # триггер остаётся тем же

jobs:
  build-and-deploy:
    # ✅ запустится ТОЛЬКО если последний коммит содержит “[build]”
    if: contains(github.event.head_commit.message, '[build]')

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build with Unity
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 2022.3.53f1
          targetPlatform: WebGL

      - name: Download Butler
        run: |
          curl -L https://broth.itch.ovh/butler/linux-amd64-headless/latest/archive/default | tar -xJ

      - name: Deploy to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.ITCHIO_API_KEY }}
        run: |
          ./butler push build/WebGL ${{ secrets.ITCHIO_USERNAME }}/${{ secrets.ITCHIO_GAME }}:web
