# .github/workflows/unity-activation.yml
name: Request Unity Manual Activation File

on:
  workflow_dispatch:

jobs:
  activation:
    name: Request .ulf file
    runs-on: ubuntu-latest
    steps:
      - name: Request manual activation file
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: 2022.3.0f1  # <-- замени на твою версию Unity
      - name: Upload license file
        uses: actions/upload-artifact@v3
        with:
          name: Unity_v2022.3.0f1.alf
          path: Unity_v2022.3.0f1.alf
